// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgVRRmAN7D3_ZBPG9EGKAPBDXF8PgEgMA',
    appId: '1:61643592236:web:01fc471c4e03b66e677789',
    messagingSenderId: '61643592236',
    projectId: 'digital-warga-pro',
    authDomain: 'digital-warga-pro.firebaseapp.com',
    storageBucket: 'digital-warga-pro.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbPCjfpgjEkEe7mENmXTU9slLHhe8PAhQ',
    appId: '1:61643592236:android:5069d7e91bcb1cf9677789',
    messagingSenderId: '61643592236',
    projectId: 'digital-warga-pro',
    storageBucket: 'digital-warga-pro.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnrxrpDyZYvVX-Ozr4tkxVu1-j6vYQSmQ',
    appId: '1:61643592236:ios:5b4fac491a7874f8677789',
    messagingSenderId: '61643592236',
    projectId: 'digital-warga-pro',
    storageBucket: 'digital-warga-pro.firebasestorage.app',
    iosBundleId: 'com.example.rtOnline',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnrxrpDyZYvVX-Ozr4tkxVu1-j6vYQSmQ',
    appId: '1:61643592236:ios:5b4fac491a7874f8677789',
    messagingSenderId: '61643592236',
    projectId: 'digital-warga-pro',
    storageBucket: 'digital-warga-pro.firebasestorage.app',
    iosBundleId: 'com.example.rtOnline',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCgVRRmAN7D3_ZBPG9EGKAPBDXF8PgEgMA',
    appId: '1:61643592236:web:cbd3c1e5c4b2005b677789',
    messagingSenderId: '61643592236',
    projectId: 'digital-warga-pro',
    authDomain: 'digital-warga-pro.firebaseapp.com',
    storageBucket: 'digital-warga-pro.firebasestorage.app',
  );
}
